<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class PreciosPlanes extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('espacios')->insert([
            ['name' => '1 BDR', 'status' =>    1, 'visible' => 1],
            ['name' => '2 BDR', 'status' =>    1, 'visible' => 1],
            ['name' => '3 BDR', 'status' =>    1, 'visible' => 1],
            ['name' => '4 BDR', 'status' =>    1, 'visible' => 1],
            ['name' => '5 BDR', 'status' =>    1, 'visible' => 1],
            ['name' => '6 BDR', 'status' =>    1, 'visible' => 1]
        ]);
        DB::table('distribucion')->insert([
            ['espacios_id' => 1, 'name' =>     '1 cama + 1 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 1, 'name' =>     '1 cama + 1.5  baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 1, 'name' =>     '1 cama + 2 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 1, 'name' =>     '2 camas + 1 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 1, 'name' =>     '2 camas + 1.5 Baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 1, 'name' =>     '2 camas + 2 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '2 camas + 1 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '2 camas + 1.5  baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '2 camas + 2 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '2 camas + 2.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '3 camas + 1 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '3 camas + 1.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '3 camas + 2 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '3 camas + 2.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '4 camas + 1 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '4 camas + 1.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '4 camas + 2 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '4 camas + 2.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '5 camas + 1 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '5 camas + 1.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '5 camas + 2 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 2, 'name' =>     '5 camas + 2.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '3 camas + 2 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '3 camas + 2.5  baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '3 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '3 camas + 3.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '4 camas + 2 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '4 camas + 2.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '4 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '4 camas + 3.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '5 camas + 2 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '5 camas + 2.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '5 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '5 camas + 3.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '6 camas + 2 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '6 camas + 2.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '6 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 3, 'name' =>     '6 camas + 3.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '4 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '4 camas + 3.5  baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '4 camas + 4 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '4 camas + 4.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '5 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '5 camas + 3.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '5 camas + 4 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '5 camas + 4.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '6 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '6 camas + 3.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '6 camas + 4 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '6 camas + 4.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '7 camas + 3 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '7 camas + 3.5 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '7 camas + 4 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 4, 'name' =>     '7 camas + 4.5 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '5 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '5 camas + 3.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '5 camas + 4 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '5 camas + 4.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '6 camas + 3 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '6 camas + 3.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '6 camas + 4 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '6 camas + 4.5 baños', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '7 camas + 3 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '7 camas + 3.5 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '7 camas + 4 baño', 'status' =>     1, 'visible' =>    1],
            ['espacios_id' => 5, 'name' =>     '7 camas + 4.5 baño', 'status' =>     1, 'visible' =>    1]

        ]);
        DB::table('area')->insert([
            ['distribucion_id' => 1, 'name' => '0 - 55m2', 'precio' =>    129, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 1, 'name' => '56 - 90 m2', 'precio' =>    149, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 1, 'name' => '90 m2 - más', 'precio' =>    169, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 2, 'name' => '0 - 55m2', 'precio' =>    135, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 2, 'name' => '56 - 90 m2', 'precio' =>    154, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 2, 'name' => '90 m2 - más', 'precio' =>    174, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 3, 'name' => '0 - 55m2', 'precio' =>    139, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 3, 'name' => '56 - 90 m2', 'precio' =>    159, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 3, 'name' => '90 m2 - más', 'precio' =>    179, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 4, 'name' => '0 - 55m2', 'precio' =>    149, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 4, 'name' => '56 - 90 m2', 'precio' =>    154, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 4, 'name' => '90 m2 - más', 'precio' =>    184, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 5, 'name' => '0 - 55m2', 'precio' =>    154, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 5, 'name' => '56 - 90 m2', 'precio' =>    169, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 5, 'name' => '90 m2 - más', 'precio' =>    189, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 6, 'name' => '0 - 55m2', 'precio' =>    159, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 6, 'name' => '56 - 90 m2', 'precio' =>    174, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 6, 'name' => '90 m2 - más', 'precio' =>    194, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 7, 'name' => '0 - 90 m2', 'precio' =>    159, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 7, 'name' => '91 - 130 m2', 'precio' =>    179, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 7, 'name' => '131- 160 m2', 'precio' =>    199, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 7, 'name' => '161 m2 - más', 'precio' =>    219, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 8, 'name' => '0 - 90 m2', 'precio' =>    164, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 8, 'name' => '91 - 130 m2', 'precio' =>    184, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 8, 'name' => '131- 160 m2', 'precio' =>    204, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 8, 'name' => '161 m2 - más', 'precio' =>    224, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 9, 'name' => '0 - 90 m2', 'precio' =>    169, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 9, 'name' => '91 - 130 m2', 'precio' =>    189, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 9, 'name' => '131- 160 m2', 'precio' =>    209, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 9, 'name' => '161 m2 - más', 'precio' =>    229, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 10, 'name' => '0 - 90 m2', 'precio' =>    174, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 10, 'name' => '91 - 130 m2', 'precio' =>    194, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 10, 'name' => '131- 160 m2', 'precio' =>    214, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 10, 'name' => '161 m2 - más', 'precio' =>    234, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 11, 'name' => '0 - 90 m2', 'precio' =>    179, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 11, 'name' => '91 - 130 m2', 'precio' =>    199, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 11, 'name' => '131- 160 m2', 'precio' =>    219, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 11, 'name' => '161 m2 - más', 'precio' =>    239, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 12, 'name' => '0 - 90 m2', 'precio' =>    184, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 12, 'name' => '91 - 130 m2', 'precio' =>    204, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 12, 'name' => '131- 160 m2', 'precio' =>    224, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 12, 'name' => '161 m2 - más', 'precio' =>    244, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 13, 'name' => '0 - 90 m2', 'precio' =>    189, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 13, 'name' => '91 - 130 m2', 'precio' =>    209, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 13, 'name' => '131- 160 m2', 'precio' =>    229, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 13, 'name' => '161 m2 - más', 'precio' =>    249, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 14, 'name' => '0 - 90 m2', 'precio' =>    194, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 14, 'name' => '91 - 130 m2', 'precio' =>    214, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 14, 'name' => '131- 160 m2', 'precio' =>    234, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 14, 'name' => '161 m2 - más', 'precio' =>    254, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 15, 'name' => '0 - 90 m2', 'precio' =>    199, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 15, 'name' => '91 - 130 m2', 'precio' =>    219, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 15, 'name' => '131- 160 m2', 'precio' =>    239, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 15, 'name' => '161 m2 - más', 'precio' =>    259, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 16, 'name' => '0 - 90 m2', 'precio' =>    204, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 16, 'name' => '91 - 130 m2', 'precio' =>    224, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 16, 'name' => '131- 160 m2', 'precio' =>    244, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 16, 'name' => '161 m2 - más', 'precio' =>    264, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 17, 'name' => '0 - 90 m2', 'precio' =>    209, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 17, 'name' => '91 - 130 m2', 'precio' =>    229, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 17, 'name' => '131- 160 m2', 'precio' =>    249, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 17, 'name' => '161 m2 - más', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 18, 'name' => '0 - 90 m2', 'precio' =>    214, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 18, 'name' => '91 - 130 m2', 'precio' =>    234, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 18, 'name' => '131- 160 m2', 'precio' =>    254, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 18, 'name' => '161 m2 - más', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 19, 'name' => '0 - 90 m2', 'precio' =>    219, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 19, 'name' => '91 - 130 m2', 'precio' =>    239, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 19, 'name' => '131- 160 m2', 'precio' =>    259, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 19, 'name' => '161 m2 - más', 'precio' =>    279, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 20, 'name' => '0 - 90 m2', 'precio' =>    224, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 20, 'name' => '91 - 130 m2', 'precio' =>    244, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 20, 'name' => '131- 160 m2', 'precio' =>    264, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 20, 'name' => '161 m2 - más', 'precio' =>    284, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 21, 'name' => '0 - 90 m2', 'precio' =>    229, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 21, 'name' => '91 - 130 m2', 'precio' =>    249, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 21, 'name' => '131- 160 m2', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 21, 'name' => '161 m2 - más', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 22, 'name' => '0 - 90 m2', 'precio' =>    234, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 22, 'name' => '91 - 130 m2', 'precio' =>    254, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 22, 'name' => '131- 160 m2', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 22, 'name' => '161 m2 - más', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 23, 'name' => '0 - 130 m2', 'precio' =>    199, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 23, 'name' => '131 - 159 m2', 'precio' =>    219, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 23, 'name' => '161 - 190 m2', 'precio' =>    239, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 23, 'name' => '191 - más m2 ', 'precio' =>    259, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 24, 'name' => '0 - 130 m2', 'precio' =>    204, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 24, 'name' => '131 - 159 m2', 'precio' =>    224, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 24, 'name' => '161 - 190 m2', 'precio' =>    244, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 24, 'name' => '191 - más m2 ', 'precio' =>    264, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 25, 'name' => '0 - 130 m2', 'precio' =>    209, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 25, 'name' => '131 - 159 m2', 'precio' =>    229, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 25, 'name' => '161 - 190 m2', 'precio' =>    249, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 25, 'name' => '191 - más m2 ', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 26, 'name' => '0 - 130 m2', 'precio' =>    214, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 26, 'name' => '131 - 159 m2', 'precio' =>    234, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 26, 'name' => '161 - 190 m2', 'precio' =>    254, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 26, 'name' => '191 - más m2 ', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 27, 'name' => '0 - 130 m2', 'precio' =>    219, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 27, 'name' => '131 - 159 m2', 'precio' =>    239, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 27, 'name' => '161 - 190 m2', 'precio' =>    259, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 27, 'name' => '191 - más m2 ', 'precio' =>    279, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 28, 'name' => '0 - 130 m2', 'precio' =>    224, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 28, 'name' => '131 - 159 m2', 'precio' =>    244, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 28, 'name' => '161 - 190 m2', 'precio' =>    264, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 28, 'name' => '191 - más m2 ', 'precio' =>    284, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 29, 'name' => '0 - 130 m2', 'precio' =>    229, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 29, 'name' => '131 - 159 m2', 'precio' =>    249, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 29, 'name' => '161 - 190 m2', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 29, 'name' => '191 - más m2 ', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 30, 'name' => '0 - 130 m2', 'precio' =>    234, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 30, 'name' => '131 - 159 m2', 'precio' =>    254, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 30, 'name' => '161 - 190 m2', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 30, 'name' => '191 - más m2 ', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 31, 'name' => '0 - 130 m2', 'precio' =>    239, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 31, 'name' => '131 - 159 m2', 'precio' =>    259, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 31, 'name' => '161 - 190 m2', 'precio' =>    279, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 31, 'name' => '191 - más m2 ', 'precio' =>    299, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 32, 'name' => '0 - 130 m2', 'precio' =>    244, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 32, 'name' => '131 - 159 m2', 'precio' =>    264, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 32, 'name' => '161 - 190 m2', 'precio' =>    284, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 32, 'name' => '191 - más m2 ', 'precio' =>    304, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 33, 'name' => '0 - 130 m2', 'precio' =>    249, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 33, 'name' => '131 - 159 m2', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 33, 'name' => '161 - 190 m2', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 33, 'name' => '191 - más m2 ', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 34, 'name' => '0 - 130 m2', 'precio' =>    254, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 34, 'name' => '131 - 159 m2', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 34, 'name' => '161 - 190 m2', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 34, 'name' => '191 - más m2 ', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 35, 'name' => '0 - 130 m2', 'precio' =>    259, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 35, 'name' => '131 - 159 m2', 'precio' =>    279, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 35, 'name' => '161 - 190 m2', 'precio' =>    299, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 35, 'name' => '191 - más m2 ', 'precio' =>    319, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 36, 'name' => '0 - 130 m2', 'precio' =>    264, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 36, 'name' => '131 - 159 m2', 'precio' =>    284, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 36, 'name' => '161 - 190 m2', 'precio' =>    304, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 36, 'name' => '191 - más m2 ', 'precio' =>    324, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 37, 'name' => '0 - 130 m2', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 37, 'name' => '131 - 159 m2', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 37, 'name' => '161 - 190 m2', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 37, 'name' => '191 - más m2 ', 'precio' =>    329, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 38, 'name' => '0 - 130 m2', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 38, 'name' => '131 - 159 m2', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 38, 'name' => '161 - 190 m2', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 38, 'name' => '191 - más m2 ', 'precio' =>    334, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 39, 'name' => '0 - 150 m2', 'precio' =>    239, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 39, 'name' => '151 - 200 m2', 'precio' =>    259, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 39, 'name' => '200- más m2', 'precio' =>    279, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 40, 'name' => '0 - 150 m2', 'precio' =>    244, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 40, 'name' => '151 - 200 m2', 'precio' =>    264, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 40, 'name' => '200- más m2', 'precio' =>    284, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 41, 'name' => '0 - 150 m2', 'precio' =>    249, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 41, 'name' => '151 - 200 m2', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 41, 'name' => '200- más m2', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 42, 'name' => '0 - 150 m2', 'precio' =>    254, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 42, 'name' => '151 - 200 m2', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 42, 'name' => '200- más m2', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 43, 'name' => '0 - 150 m2', 'precio' =>    259, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 43, 'name' => '151 - 200 m2', 'precio' =>    279, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 43, 'name' => '200- más m2', 'precio' =>    299, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 44, 'name' => '0 - 150 m2', 'precio' =>    264, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 44, 'name' => '151 - 200 m2', 'precio' =>    284, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 44, 'name' => '200- más m2', 'precio' =>    304, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 45, 'name' => '0 - 150 m2', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 45, 'name' => '151 - 200 m2', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 45, 'name' => '200- más m2', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 46, 'name' => '0 - 150 m2', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 46, 'name' => '151 - 200 m2', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 46, 'name' => '200- más m2', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 47, 'name' => '0 - 150 m2', 'precio' =>    279, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 47, 'name' => '151 - 200 m2', 'precio' =>    299, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 47, 'name' => '200- más m2', 'precio' =>    319, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 48, 'name' => '0 - 150 m2', 'precio' =>    284, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 48, 'name' => '151 - 200 m2', 'precio' =>    304, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 48, 'name' => '200- más m2', 'precio' =>    324, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 49, 'name' => '0 - 150 m2', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 49, 'name' => '151 - 200 m2', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 49, 'name' => '200- más m2', 'precio' =>    329, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 50, 'name' => '0 - 150 m2', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 50, 'name' => '151 - 200 m2', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 50, 'name' => '200- más m2', 'precio' =>    334, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 51, 'name' => '0 - 150 m2', 'precio' =>    299, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 51, 'name' => '151 - 200 m2', 'precio' =>    319, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 51, 'name' => '200- más m2', 'precio' =>    339, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 52, 'name' => '0 - 150 m2', 'precio' =>    304, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 52, 'name' => '151 - 200 m2', 'precio' =>    324, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 52, 'name' => '200- más m2', 'precio' =>    344, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 53, 'name' => '0 - 150 m2', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 53, 'name' => '151 - 200 m2', 'precio' =>    329, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 53, 'name' => '200- más m2', 'precio' =>    349, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 54, 'name' => '0 - 150 m2', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 54, 'name' => '151 - 200 m2', 'precio' =>    334, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 54, 'name' => '200- más m2', 'precio' =>    354, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 55, 'name' => '0 - 150 m2', 'precio' =>    269, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 55, 'name' => '151 - 200 m2', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 55, 'name' => '200- más m2', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 56, 'name' => '0 - 150 m2', 'precio' =>    274, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 56, 'name' => '151 - 200 m2', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 56, 'name' => '200- más m2', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 57, 'name' => '0 - 150 m2', 'precio' =>    279, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 57, 'name' => '151 - 200 m2', 'precio' =>    299, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 57, 'name' => '200- más m2', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 58, 'name' => '0 - 150 m2', 'precio' =>    284, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 58, 'name' => '151 - 200 m2', 'precio' =>    304, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 58, 'name' => '200- más m2', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 59, 'name' => '0 - 150 m2', 'precio' =>    289, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 59, 'name' => '151 - 200 m2', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 59, 'name' => '200- más m2', 'precio' =>    319, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 60, 'name' => '0 - 150 m2', 'precio' =>    294, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 60, 'name' => '151 - 200 m2', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 60, 'name' => '200- más m2', 'precio' =>    324, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 61, 'name' => '0 - 150 m2', 'precio' =>    299, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 61, 'name' => '151 - 200 m2', 'precio' =>    319, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 61, 'name' => '200- más m2', 'precio' =>    329, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 62, 'name' => '0 - 150 m2', 'precio' =>    304, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 62, 'name' => '151 - 200 m2', 'precio' =>    324, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 62, 'name' => '200- más m2', 'precio' =>    334, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 63, 'name' => '0 - 150 m2', 'precio' =>    309, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 63, 'name' => '151 - 200 m2', 'precio' =>    329, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 63, 'name' => '200- más m2', 'precio' =>    339, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 64, 'name' => '0 - 150 m2', 'precio' =>    314, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 64, 'name' => '151 - 200 m2', 'precio' =>    334, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 64, 'name' => '200- más m2', 'precio' =>    344, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 65, 'name' => '0 - 150 m2', 'precio' =>    319, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 65, 'name' => '151 - 200 m2', 'precio' =>    339, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 65, 'name' => '200- más m2', 'precio' =>    349, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 66, 'name' => '0 - 150 m2', 'precio' =>    324, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 66, 'name' => '151 - 200 m2', 'precio' =>    344, 'status' =>    1, 'visible' =>    1],
            ['distribucion_id' => 66, 'name' => '200- más m2', 'precio' =>    354, 'status' =>    1, 'visible' =>    1]
        ]);
    }
}
